// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dsmm_server.Data;

namespace dsmm_server.Migrations.MMdbMigrations
{
    [DbContext(typeof(MMdb))]
    partial class MMdbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview7.19362.6");

            modelBuilder.Entity("dsmm_server.Data.MMdbPlayer", b =>
                {
                    b.Property<int>("MMdbPlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthName");

                    b.Property<bool>("Credential");

                    b.Property<bool>("Deleted");

                    b.Property<bool>("Ladder");

                    b.Property<DateTime>("MMDeleted");

                    b.Property<string>("Mode");

                    b.Property<string>("Mode2");

                    b.Property<string>("Name");

                    b.Property<string>("Server");

                    b.HasKey("MMdbPlayerId");

                    b.ToTable("MMdbPlayers");
                });

            modelBuilder.Entity("dsmm_server.Data.MMdbRace", b =>
                {
                    b.Property<int>("MMdbRaceId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthName");

                    b.Property<bool>("Credential");

                    b.Property<bool>("Deleted");

                    b.Property<bool>("Ladder");

                    b.Property<DateTime>("MMDeleted");

                    b.Property<string>("Mode");

                    b.Property<string>("Mode2");

                    b.Property<string>("Name");

                    b.Property<string>("Server");

                    b.HasKey("MMdbRaceId");

                    b.ToTable("MMdbRaces");
                });

            modelBuilder.Entity("dsmm_server.Data.MMdbRaceRating", b =>
                {
                    b.Property<int>("MMdbRaceRatingId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("EXP");

                    b.Property<int>("Games");

                    b.Property<string>("Lobby");

                    b.Property<int>("MMdbRaceId");

                    b.Property<double>("MU");

                    b.Property<double>("SIGMA");

                    b.HasKey("MMdbRaceRatingId");

                    b.HasIndex("MMdbRaceId");

                    b.ToTable("MMdbRaceRatings");
                });

            modelBuilder.Entity("dsmm_server.Data.MMdbRating", b =>
                {
                    b.Property<int>("MMdbRatingId")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("EXP");

                    b.Property<int>("Games");

                    b.Property<string>("Lobby");

                    b.Property<int>("MMdbPlayerId");

                    b.Property<double>("MU");

                    b.Property<double>("SIGMA");

                    b.HasKey("MMdbRatingId");

                    b.HasIndex("MMdbPlayerId");

                    b.ToTable("MMdbRatings");
                });

            modelBuilder.Entity("dsmm_server.Data.MMdbRaceRating", b =>
                {
                    b.HasOne("dsmm_server.Data.MMdbRace", "MMdbRace")
                        .WithMany("MMdbRaceRatings")
                        .HasForeignKey("MMdbRaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dsmm_server.Data.MMdbRating", b =>
                {
                    b.HasOne("dsmm_server.Data.MMdbPlayer", "MMdbPlayer")
                        .WithMany("MMdbRatings")
                        .HasForeignKey("MMdbPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
